---

- src: "https://github.com/nexcess/ansible-role-puppet.git"
  name: "nexcess.puppet"
- src: "https://github.com/nexcess/ansible-role-server.git"
  name: "nexcess.server"
- src: "https://github.com/nexcess/ansible-role-apache.git"
  name: "nexcess.apache"
- src: "https://github.com/nexcess/ansible-role-apache-php-fpm.git"
  name: "nexcess.apache-php-fpm"
- src: "https://github.com/nexcess/ansible-haproxy.git"
  name: "nexcess.haproxy"
- src: "https://github.com/nexcess/ansible-role-repo-percona.git"
  name: "nexcess.repo-percona"
- src: "https://github.com/nexcess/ansible-role-mysql.git"
  name: "nexcess.mysql"
- src: "https://github.com/nexcess/ansible-role-nfs2.git"
  name: "nexcess.nfs"
- src: "https://github.com/nexcess/ansible-role-php.git"
  name: "nexcess.php"
- src: "https://github.com/nexcess/ansible-role-ssl-cert.git"
  name: "nexcess.ssl-cert"
- src: "https://github.com/nexcess/ansible-role-composer.git"
  name: "nexcess.composer"
- src: "https://github.com/nexpoehler/ansible-role-magento.git"
  name: "nexcess.magento2"
  version: "base-url-override"
- src: "https://github.com/nexcess/ansible-redis"
  name: "nexcess.redis"
- src: "https://github.com/nexcess/ansible-role-varnish.git"
  name: "nexcess.varnish"
