---

- include: user.yml
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"
    
- name: Make Sure php-fpm is Started
  service:
    name="{{ php_prefix }}-php-fpm"
    state="started"
    enabled="yes"
  when: mode == "post"

- name: Mount NFS Shared
  mount:
    name="/shared"
    src="{{ fs_backnet_addrs[0] }}:/shared"
    fstype="nfs"
    opts="defaults"
    dump="0"
    passno="2"
    state="mounted"
  when:
    - mode == "post"
    - nex_env_target != "vagrant"

