---

- name: Allow Haproxy To Bind On Port haproxy stats port
  seport:
    ports="{{ haproxy_stats_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  tags: "lb"
  when: mode == "pre"

- name: Ensure Haproxy Chroot Dev Dir Exists
  file:
    name="{{ haproxy_global.chroot }}/dev"
    state="directory"

- name: Install Haproxy Rsyslog Config
  template: 
    src="haproxy-rsyslog.conf.j2"
    dest="/etc/rsyslog.d/haproxy.conf"

- name: Restart Rsyslog
  service:
    name="rsyslog"
    state="restarted"
