---

- include: lb-all.yml
  tags: "lb"
  when: nex_env_target != "vagrant"

- name: Reformat external Dicts For HAProxy (with varnish)
  set_fact:
    haproxy_external_servers="{{ haproxy_external_servers | default([]) + [ dict(name=item1,ip=item1,port=lb_varnish_port,params=[]) ] }}"
  with_items: "{{ lb_varnish_backnet_addrs }}"
  loop_control:
    loop_var: "item1"
  tags: "lb"
  when:
    - mode == "pre"    
    - lb_varnish_backnet_addrs is defined
  run_once: true

- name: Reformat external Dicts For HAProxy (without varnish)
  set_fact:
    haproxy_external_servers="{{ haproxy_external_servers | default([]) + [ dict(name=item2,ip=item2,port=lb_web_port,params=[]) ] }}"
  with_items: "{{ lb_web_backnet_addrs }}"
  loop_control:
    loop_var: "item2"
  tags: "lb"
  when:
    - mode == "pre"    
    - lb_varnish_backnet_addrs is not defined
  run_once: true

- name: "Define haproxy_frontends"
  set_fact:
    haproxy_frontends: "{{ lb_ext_haproxy_frontends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"

- name: "Define haproxy_backends"
  set_fact:
    haproxy_backends: "{{ lb_ext_haproxy_backends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"
    
- name: "Define haproxy_global"
  set_fact:
    haproxy_global: "{{ lb_ext_haproxy_global }}"
  when:
    - mode == "pre"
    - lb_ext_haproxy_global is defined
