---

- include: lb-all.yml
  tags: "lb"
  when: nex_env_target != "vagrant"
  
- name: Reformat FPM Dicts For HAProxy
  set_fact:
    haproxy_fpm_servers="{{ haproxy_fpm_servers | default([]) + [ dict(name=ip_item,ip=ip_item,port=php_fpm_port,params=[]) ] }}"
  with_items: "{{ fpm_backnet_addrs }}"
  loop_control:
    loop_var: ip_item
  tags: "lb"
  when: mode == "pre"
  run_once: true

- name: Allow Haproxy To Bind On LB php-fpm Port
  seport:
    ports="{{ lb_php_fpm_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  tags: "lb"
  when: mode == "pre"

- name: "Define haproxy_frontends"
  set_fact:
    haproxy_frontends: "{{ lb_fpm_haproxy_frontends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"

- name: "Define haproxy_backends"
  set_fact:
    haproxy_backends: "{{ lb_fpm_haproxy_backends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"
