---
- include: lb-all.yml
  tags: "lb"
  when: nex_env_target != "vagrant"
  
- name: Reformat Webserver Dicts For HAProxy
  set_fact:
    haproxy_web_servers="{{ haproxy_web_servers | default([]) + [ dict(name=ip_item,ip=ip_item,port=web_port,params=[]) ] }}"
  with_items: "{{ web_backnet_addrs }}"
  loop_control:
    loop_var: ip_item
  tags: "lb"
  when: mode == "pre"
  run_once: true

- name: Allow Haproxy To Bind On Backend Web Port
  seport:
    ports="{{ lb_web_port }}"
    proto="tcp"
    setype="http_port_t"
    state="present"
  tags: "lb"
  when: mode == "pre"

- name: "Define haproxy_frontends"
  set_fact:
    haproxy_frontends: "{{ lb_web_haproxy_frontends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"

- name: "Define haproxy_backends"
  set_fact:
    haproxy_backends: "{{ lb_web_haproxy_backends }}"
  when:
    - mode == "pre"
    - nex_env_target != "vagrant"
    
