---

- include: lb-all.yml
  tags: "lb"

- include: lb-web.yml
  tags: "lb"

- include: lb-fpm.yml
  tags: "lb"

- include: lb-external.yml
  tags: "lb"

- include: lb-redis.yml
  tags: "lb"

- include: lb-varnish.yml
  tags: "lb"
  
- include: user.yml
  when: mode == "pre"

- include: web.yml
  tags: "web"

- include: fpm.yml
  tags: "fpm"

- include: fs.yml
  tags: "fs"

- include: db.yml
  tags: "db"

- include: varnish.yml
  tags: "varnish"

- include: redis.yml
  tags: "redis"

- name: "Combine haproxy_frontends"
  set_fact:
    haproxy_frontends: "{{ lb_ext_haproxy_frontends + lb_fpm_haproxy_frontends + lb_redis_haproxy_frontends + lb_web_haproxy_frontends }}"
  when: mode == "pre"
  run_once: true

- name: "Add lb_varnish into haproxy_frontends"
  set_fact:
    haproxy_frontends: "{{ haproxy_frontends + lb_varnish_haproxy_frontends }}"
  when:
    - mode == "pre"
    - lb_varnish_haproxy_frontends is defined
  run_once: true

- name: "Combine haproxy_backends"
  set_fact:
    haproxy_backends: "{{ lb_ext_haproxy_backends + lb_fpm_haproxy_backends + lb_redis_haproxy_backends + lb_web_haproxy_backends }}"
  when: mode == "pre"
  run_once: true

- name: "Add lb_varnish into haproxy_backends"
  set_fact:
    haproxy_backends: "{{ haproxy_backends + lb_varnish_haproxy_backends }}"
  when:
    - mode == "pre"
    - lb_varnish_haproxy_backends is defined
  run_once: true
