---

- name: Setup All The Servers
  hosts: fs:web:fpm:db:varnish:redis:lb-web:lb-fpm:lb-varnish:lb-redis:lb-external
  become: true
  any_errors_fatal: true
  strategy: free
  pre_tasks:
    - include: tasks/{{ item }}.yml mode="pre"
      with_items: "{{ group_names }}"
      static: no
      when: nex_env_target != 'vagrant'
    - include: tasks/vagrant.yml mode="pre"
      when: nex_env_target == 'vagrant'
    - include_vars: vagrant.yml
      when: nex_env_target == 'vagrant'

  roles:
    - { role: nexcess.server, tags: ["server"] }

    - { role: nexcess.apache, when: "'web' in group_names", tags: ["web"] }
    - { role: nexcess.nfs,    when: "'web' in group_names or 'fpm' in group_names", tags: ["web"] }

    - { role: nexcess.repo-percona, when: "'db' in group_names", tags: ["db"] }
    - { role: nexcess.mysql,        when: "'db' in group_names", tags: ["db"] }

    - { role: nexcess.php,      when: "'fpm' in group_names or 'fs' in group_names", tags: ["fpm"] }
    - { role: nexcess.composer, when: "'fpm' in group_names or 'fs' in group_names", tags: ["fpm"] }

    - { role: nexcess.varnish, when: "'varnish' in group_names", tags: ["varnish"] }

    - { role: nexcess.redis, when: "'redis' in group_names", tags: ["redis"] }

    - { role: nexcess.ssl-cert, when: "'lb-external' in group_names", tags: ["lb"] }
    - { role: nexcess.haproxy,  when: "'lb-external' in group_names or 'lb-fpm' in group_names or 'lb-redis' in group_names or 'lb-varnish' in group_names or 'lb-web' in group_names", tags: ["lb"] }

    - { role: "{{ nex_app }}", mode: "env" }

    - { role: nexcess.puppet, when: "nex_env_target != 'vagrant'" }
    
  post_tasks:
    - include: tasks/{{ item }}.yml mode="post"
      with_items: "{{ group_names }}"
      static: no
